name: nomadik
version: 1.4.3
base: core22
summary: Hashicorp Nomad packaged as Snap
description: |
  Since the snap named `nomad` was taken, I created `nomadik` so I can support IoT, On Premise and Edge Computing workloads on multiple platforms with Hashicorp's Nomad.

  Hashicorp's website describes `nomad` on https://developer.hashicorp.com/nomad as:

  "A simple and flexible scheduler and orchestrator to deploy and manage containers and non-containerized applications across on-prem and clouds at scale."

  Github repository of my published Snaps (including this one): https://github.com/williamcharltonengineering/snaps

contact: will@williamcharltonengineering.com
issues: https://github.com/williamcharltonengineering/snaps/issues
source-code: https://github.com/williamcharltonengineering/snaps
website: https://williamcharltonengineering.com

type: app
grade: devel
architectures:
  - build-on: amd64
    build-for: amd64

confinement: strict

plugs:
  nomadik-config:
    interface: personal-files
    read:
    - $HOME/nomad

apps:
  nomad:
    command: nomad agent -config nomad/config.hcl
    daemon: simple
    plugs:
      - network
      - home
      - nomadik-config

parts:
  nomad:
    plugin: nil
    override-build: |
      set -x
      curl \
        --retry 3 \
        --fail \
        -SL \
        -o nomad_$SNAPCRAFT_PROJECT_VERSION_linux_$SNAPCRAFT_TARGET_ARCH.zip \
        https://releases.hashicorp.com/nomad/$SNAPCRAFT_PROJECT_VERSION/nomad_$SNAPCRAFT_PROJECT_VERSION_linux_$SNAPCRAFT_TARGET_ARCH.zip
      # source-checksum: sha256/21b3afc78bca4789ac271a855e2c4a993876d0d3f84499692d0d9dc5c8abf9ca
      unzip -o nomad_$SNAPCRAFT_PROJECT_VERSION_linux_$SNAPCRAFT_TARGET_ARCH.zip -d ../install

build-packages:
  - curl
  - unzip
