name: Publish Snaps

on: push

jobs:
  snapcraft:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft and Login
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_nomadik_token }}
          use_lxd: true

      - name: Build nomadik
        uses: snapcore/action-build@v1
        with:
          path: nomad
        # run: |
        #   cd nomad
        #   sg lxd -c 'snapcraft'
