name: Publish Snaps

on: push

jobs:
  snapcraft:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build nomadik
        uses: snapcore/action-build@v1
        with:
          path: nomad

      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT_NOMADIK_TOKEN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
