name: Publish Snaps

on: push

jobs:
  snapcraft:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft and Login
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_nomadik_token }}

      - name: Build nomadik
        run: |
          cd nomad
          snapcraft
